server:
  port: 8080

spring:
  application:
    name: api-gateway
  datasource:
    url: jdbc:postgresql://localhost:5432/miniuber
    username: miniuber
    password: miniuber123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ride-matching-group
      auto-offset-reset: earliest