server:
  port: 8083
  tomcat:
    threads:
      max: 800         # Default is 200. Allows more simultaneous HTTP requests.
    accept-count: 1000 # Default is 100. Increases the waiting queue size.

spring:
  application:
    name: pricing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/miniuber
    username: miniuber
    password: miniuber123
    hikari:
      maximum-pool-size: 50   # Default is 10. Allows more simultaneous DB writes.
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ride-matching-group
      auto-offset-reset: earliest