server:
  port: 8084

spring:
  application:
    name: trip-service

  datasource:
    url: jdbc:postgresql://localhost:5432/miniuber
    username: miniuber
    password: miniuber123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: trip-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.miniuber.*"
        spring.json.use.type.headers: false          # ← ignore the producer's class name header
        spring.json.value.default.type: com.miniuber.trip.event.RideMatchedEvent  # ← use this instead
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    com.miniuber: DEBUG
    org.springframework.kafka: INFO